name: Go CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci: 
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
        with:
          args: --timeout=5m
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
  build_test:
    runs-on: ubuntu-latest
    needs:
      - golangci
    steps:
        - uses: actions/checkout@v4
        - name: Set up Go
          uses: actions/setup-go@v5.0.2
          with:
            go-version: ^1.19
          id: go
        - name: Get and verify dependencies
          run: go mod download && go mod verify

        - name: Build app to make sure there are zero issues
          run: go build -o hraft

        - name: Build and test
          id: build-test
          run: |
            go vet ./...
            go test -timeout 60s -v ./... -coverprofile=coverage.txt -covermode=atomic
            go test -race -timeout 120s -v ./...